# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

# Training parameters:
training:
  problem:
    categories: C1

# Validation parameters:
validation:
  problem:
    categories: C1

pipeline:
  name: vqa_med_c1_classification_image_cnn_softmax

  # Image encoder.
  image_encoder:
    type: ConvNetEncoder
    priority: 1.1
    streams:
      inputs: images

  # Reshape inputs
  reshaper:
    type: ReshapeTensor
    input_dims: [-1, 16, 26, 26]
    output_dims: [-1, 10816]
    priority: 1.2
    streams:
      inputs: feature_maps
      outputs: reshaped_maps
    globals:
      output_size: reshaped_maps_size

  # Answer encoding.
  answer_indexer:
    type: LabelIndexer
    priority: 2
    data_folder: &data_folder ~/data/vqa-med
    word_mappings_file: answers.c1.word.mappings.csv
    # Export mappings and size to globals.
    export_word_mappings_to_globals: True
    streams:
      inputs: answers
      outputs: answers_ids
    globals:
      vocabulary_size: vocabulary_size_ci1
      word_mappings: word_mappings_c1

  # Model - image classifier.
  classifier:
    type: SoftmaxClassifier 
    hidden_sizes: [1000]
    priority: 3
    streams:
      inputs: reshaped_maps
    globals:
      input_size: reshaped_maps_size
      prediction_size: vocabulary_size_ci1
  
  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 4
    # Use the same word mappings as label indexer.
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: predicted_answers
    globals:
      vocabulary_size: vocabulary_size_ci1
      word_mappings: word_mappings_c1

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    targets_dim: 1
    streams:
      targets: answers_ids
      loss: loss

  # Statistics.
  accuracy:
    type: Accuracy
    priority: 10
    streams:
      targets: answers_ids
  batch_size:
    type: BatchSize
    priority: 11

  # Viewers.
  viewer:
    type: StreamViewer
    priority: 12
    stream_names: questions,category_names,answers,predicted_answers

  #: pipeline
