# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

# Training parameters:
training:
  problem:
    categories: C1

# Validation parameters:
validation:
  problem:
    categories: C1

pipeline:
  name: vqa_med_c1_classification_question_rnn
  #load: /users/tomaszkornuta/experiments/dummylanguageidentification/language_classifier/20190301_145416/checkpoints/language_classifier_best.pt
  #freeze: True
  #disable: prediction_decoder,accuracy

  # Questions encoding.
  question_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  # Model 2: Embeddings
  question_embeddings:
    type: SentenceEmbeddings
    priority: 1.2
    embeddings_size: 50
    pretrained_embeddings_file: glove.6B.50d.txt
    data_folder: &data_folder ~/data/vqa-med
    word_mappings_file: questions.all.word.mappings.csv
    streams:
      inputs: tokenized_questions
      outputs: embedded_questions      
  
  # Answer encoding.
  answer_indexer:
    type: LabelIndexer
    priority: 2
    data_folder: *data_folder
    # Export mappings and size to globals.
    export_word_mappings_to_globals: True
    word_mappings_file: answers.c1.word.mappings.csv
    streams:
      inputs: answers
      outputs: answers_ids
    globals:
      vocabulary_size: vocabulary_size_ci1
      word_mappings: word_mappings_c1

  # Model 2: RNN
  lstm:
    type: RNN
    cell_type: LSTM
    prediction_mode: Last
    priority: 3
    initial_state_trainable: False
    #num_layers: 5
    hidden_size: 50
    streams:
      inputs: embedded_questions
    globals:
      input_size: embeddings_size
      prediction_size: vocabulary_size_ci1

  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 4
    # Use the same word mappings as label indexer.
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: predicted_answers
    globals:
      vocabulary_size: vocabulary_size_ci1
      word_mappings: word_mappings_c1

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    targets_dim: 1
    streams:
      targets: answers_ids
      loss: loss

  # Statistics.
  accuracy:
    type: Accuracy
    priority: 10
    streams:
      targets: answers_ids
  batch_size:
    type: BatchSize
    priority: 11

  # Viewers.
  viewer:
    type: StreamViewer
    priority: 12
    stream_names: questions,category_names,answers,predicted_answers

  #: pipeline
