# Training parameters:
training:
  task:
    type: &p_type VQAMED2019
    data_folder: &data_folder ~/data/vqa-med
    split: training_validation
    resize_image: &resize_image [224, 224]
    batch_size:  64
    # Generate and export shuffled indices.
    shuffle_indices: True
    export_indices: shuffled_indices.npy

  # Default sampler during training.
  sampler:
    type: kFoldWeightedRandomSampler
    folds: 20
    epochs_per_fold: 1000 # NEVER CHANGE FOLD!
  # Use four workers for loading images.
  dataloader:
    num_workers: 4

  # Optimizer parameters:
  optimizer:
    type: Adam
    lr: 0.0001

  # Terminal conditions:
  terminal_conditions:
    loss_stop_threshold: 1.0e-3
    episode_limit: 10000
    epoch_limit: -1

# Validation parameters:
validation:
  partial_validation_interval: 10
  task:
    type: *p_type
    data_folder: *data_folder
    split: training_validation
    resize_image: *resize_image     
    batch_size:  64
    # Import shuffled indices.
    import_indices: shuffled_indices.npy

  # Default sampler during validation.
  sampler:
    type: kFoldRandomSampler
    folds: 20
    epochs_per_fold: 1000 # NEVER CHANGE FOLD!
  # Use four workers for loading images.
  dataloader:
    num_workers: 4
