# This config is not a standalone config!
# It adds new sections (sets) without samplers and components for saving answers that we can use for getting final answers.

training_answers:
  problem:
    type: &p_type VQAMED2019
    data_folder: &data_folder ~/data/vqa-med
    split: training
    categories: all
    resize_image: &resize_image [224, 224]
    batch_size: 64
  # No sampler, process samples in the same order.
  dataloader:
    shuffle: False
  # Use four workers for loading images.
  dataloader:
    num_workers: 4

validation_answers:
  problem:
    type: *p_type
    data_folder: *data_folder
    split: validation
    resize_image: *resize_image     
    batch_size: 64
  # No sampler, process samples in the same order.
  dataloader:
    shuffle: False
  # Use four workers for loading images.
  dataloader:
    num_workers: 4


# Testing parameters:
test_answers:
  problem:
    type: *p_type 
    data_folder: *data_folder
    split: test
    resize_image: *resize_image     
    batch_size: 64
  # No sampler, process samples in the same order.
  dataloader:
    shuffle: False
  # Use four workers for loading images.
  dataloader:
    num_workers: 4

# Add component for exporting answers to files.
pipeline:
  disable: viewer
#  # Viewers.
  viewer_extended:
    type: StreamViewer
    priority: 100.4
    input_streams: indices,image_ids,questions,category_names,predicted_categories

#: pipeline
