# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

pipeline:
  name: vqa_med_question_categorization_rnn
  #load: /users/tomaszkornuta/experiments/dummylanguageidentification/language_classifier/20190301_145416/checkpoints/language_classifier_best.pt
  #freeze: True
  #disable: prediction_decoder,accuracy

  # Questions encoding.
  question_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  # Model 2: Embeddings
  question_embedding:
    type: SentenceEmbeddings
    priority: 1.2
    embeddings_size: 50
    pretrained_embeddings_file: glove.6B.50d.txt
    data_folder: ~/data/vqa-med
    word_mappings_file: question.all.vocabulary.mappings.csv
    streams:
      inputs: tokenized_questions
      outputs: embedded_questions      
  
  # Model 2: RNN
  lstm:
    type: RNN
    cell_type: LSTM
    prediction_mode: Last
    priority: 3
    initial_state_trainable: False
    #num_layers: 5
    #hidden_size: 1000
    streams:
      inputs: embedded_questions
    globals:
      input_size: embeddings_size
      prediction_size: num_categories # C1,C2,C3,C4

  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 4
    # Use the same word mappings as label indexer.
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: predicted_categories
    globals:
      vocabulary_size: num_categories
      word_mappings: category_word_mappings

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    targets_dim: 1
    streams:
      targets: category_ids
      loss: loss

  # Statistics.
  accuracy:
    type: Accuracy
    priority: 10
    streams:
      targets: category_ids
  batch_size:
    type: BatchSize
    priority: 11

  # Viewers.
  viewer:
    type: StreamViewer
    priority: 12
    stream_names: questions,category_names,predicted_categories

  #: pipeline
