# Training parameters:
training:
  problem:
    type: &p_type VQAMED2019
    data_folder: &data_folder ~/data/vqa-med
    split: training
    resize_image: &resize_image [224, 224]
    batch_size:  64

  # optimizer parameters:
  optimizer:
    name: Adam
    lr: 0.1

  # settings parameters
  terminal_conditions:
    loss_stop: 1.0e-2
    episode_limit: 10000
    epoch_limit: 100

# Validation parameters:
validation:
  partial_validation_interval: 10
  problem:
    type: *p_type
    data_folder: *data_folder
    split: validation
    resize_image: *resize_image     
    batch_size:  64

# Testing parameters:
testing:
  problem:
    type: *p_type 
    data_folder: *data_folder
    split: test
    resize_image: *resize_image     
    batch_size: 64

pipeline:
  name: vqa_med_question_categorization
  #load: /users/tomaszkornuta/experiments/dummylanguageidentification/language_classifier/20190301_145416/checkpoints/language_classifier_best.pt
  #freeze: True
  #disable: prediction_decoder,accuracy

  # Questions encoding.
  sentence_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  source_indexer:
    type: SentenceIndexer
    priority: 1.2
    data_folder: *data_folder
    source_files: wiki.train.tokens,wiki.valid.tokens,wiki.test.tokens
    encodings_file: wiki.all.tokenized_words
    additional_tokens: <eos>
    streams:
      inputs: tokenized_questions
      outputs: indexed_questions
    globals:
      sentence_vocab_size: questions_vocab_size
  
  # Model 1: index embeddings.
  source_embedder:
    type: IndexEmbeddings
    priority: 1.3
    embeddings_size: 100
    streams:
      inputs: indexed_questions
      outputs: embedded_questions
    globals:
      vocab_size: questions_vocab_size
      
  
  # Model 3: RNN
  lstm:
    type: RNN
    #freeze: True
    disable: True
    priority: 3
    #initial_state_trainable: False
    streams:
      inputs: embedded_sources
    globals:
      input_size: embeddings_size
      prediction_size: num_categories # C1,C2,C3,C4

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    targets_dim: 2
    streams:
      targets: indexed_targets
      loss: loss

  #: pipeline
