# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

pipeline:
  name: vqa_med_question_categorization_onehot_bow

  # Questions encoding.
  question_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  sentence_encoder:
    type: SentenceOneHotEncoder
    priority: 1.2
    data_folder: ~/data/vqa-med
    word_mappings_file: question.all.vocabulary.mappings.csv
    streams:
      inputs: tokenized_questions
      outputs: encoded_questions
    globals:
      vocabulary_size: sentence_vocabulary_size

  bow_encoder:
    type: BOWEncoder
    priority: 1.3
    streams:
      inputs: encoded_questions
      outputs: bow_questions
    globals:
        bow_size: sentence_vocabulary_size # Set by sentence_encoder.

  # Model
  classifier:
    type: SoftmaxClassifier
    #freeze: True
    priority: 3
    streams:
      inputs: bow_questions
    globals:
      input_size: sentence_vocabulary_size # Set by sentence_encoder.
      prediction_size: num_categories # C1,C2,C3,C4

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    targets_dim: 1
    streams:
      targets: categories
      loss: loss

  # Statistics.
  accuracy:
    type: Accuracy
    priority: 10
    streams:
      targets: categories

  #: pipeline
