# This file defines the default values for the String To Mask component.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Value that will be used when word is out of vocavbulary (LOADED)
# (Mask for that element will be 0 as well)
out_of_vocabulary_value: -1

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing input strings (INPUT)
  strings: strings

  # Stream containing output masks (OUTPUT)
  masks: masks

  # Stream containing output indices (OUTPUT)
  string_indices: string_indices

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Vocabulary used to produce masks and indices (GET)
  word_mappings: word_mappings

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

