# This file defines the default values for the List to Tensor transformation.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Number of input dimensions, including last tensor (LOADED)
num_inputs_dims: 1

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing input tensor (INPUT)
  inputs: inputs

  # Stream containing output tensor (OUTPUT)
  outputs: outputs

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Size of the intput_item (GET)
  # (last dimenstion)
  input_size: input_size

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

