# This file defines the default values for the MNIST problem.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Dimensions of the input tensor (LOADED)
# Specific to a task/model, must be set by user (no DEFAULT)
# input_dims: [BATCH x ....]

# Dimensions of the input tensor (LOADED)
# Specific to a task/model, must be set by user (no DEFAULT)
# output_dims: [BATCH x ....]

keymappings: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing input tensor (INPUT)
  inputs: inputs

  # Stream containing output tensor (OUTPUT)
  outputs: outputs

  ####################################################################
  # 3. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Size of the output tensor (all dimensions except batch_size)
  output_size: output_size

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be RETRIEVED.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

