# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

# Training parameters:
training:
  problem:
    categories: C2
    export_sample_weights: ~/data/vqa-med/answers.c2.weights.csv
  sampler:
    weights: ~/data/vqa-med/answers.c2.weights.csv

# Validation parameters:
validation:
  problem:
    categories: C2


pipeline:

  # Answer encoding.
  answer_indexer:
    type: LabelIndexer
    priority: 0.1
    data_folder: ~/data/vqa-med
    word_mappings_file: answers.c2.word.mappings.csv
    # Export mappings and size to globals.
    export_word_mappings_to_globals: True
    streams:
      inputs: answers
      outputs: answers_ids
    globals:
      vocabulary_size: vocabulary_size_c2
      word_mappings: word_mappings_c2


  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 10.1
    # Use the same word mappings as label indexer.
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: predicted_answers
    globals:
      vocabulary_size: vocabulary_size_c2
      word_mappings: word_mappings_c2

  # Loss
  nllloss:
    type: NLLLoss
    priority: 10.2
    targets_dim: 1
    streams:
      targets: answers_ids
      loss: loss

  # Statistics.
  batch_size:
    type: BatchSizeStatistics
    priority: 100.1

  #accuracy:
  #  type: AccuracyStatistics
  #  priority: 100.2
  #  streams:
  #    targets: answers_ids

  precision_recall:
    type: PrecisionRecallStatistics
    priority: 100.3
    use_word_mappings: True
    show_class_scores: True
    show_confusion_matrix: True
    streams:
      targets: answers_ids
    globals:
      word_mappings: word_mappings_c2
      num_classes: vocabulary_size_c2

  # Viewers.
  viewer:
    type: StreamViewer
    priority: 100.4
    input_streams: questions,tokenized_questions,category_names,answers,predicted_answers

#: pipeline
