  # Training parameters:
training:
  problem:
    type: &p_type WiLYLanguageIdentification
    data_folder: &data_folder '~/data/language_identification/wily'
    batch_size:  64
    keymappings: &p_keymappings
      inputs: sentences
      targets: languages

  # Use sampler that operates on a subset.
  sampler:
    name: SubsetRandomSampler
    indices: [0, 117000]

  # optimizer parameters:
  optimizer:
    name: Adam
    lr: 0.1

  # settings parameters
  terminal_conditions:
    loss_stop: 1.0e-2
    episode_limit: 10000
    epoch_limit: 100

# Validation parameters:
validation:
  partial_validation_interval: 10
  problem:
    type: *p_type
    data_folder: *data_folder
    batch_size:  64
    keymappings: *p_keymappings

  # Use sampler that operates on a subset.
  sampler:
    name: SubsetRandomSampler
    indices: [117000, 117500]

# Testing parameters:
testing:
  problem:
    type: *p_type 
    data_folder: *data_folder
    batch_size: 64
    use_train_data: False
    keymappings: *p_keymappings

pipeline:
  name: language_classifier
  #load: /users/tomaszkornuta/experiments/dummylanguageidentification/language_classifier/20190301_145416/checkpoints/language_classifier_best.pt
  #freeze: True
  #disable: prediction_decoder,accuracy
  # Sentences encoding.
  sentence_tokenizer:
    type: SentenceTokenizer
    priority: 1
    keymappings: 
      inputs: sentences
      outputs: tokenized_sentences
  sentence_encoder:
    type: SentenceEncoder
    priority: 2
    data_folder: ~/data/language_identification/wily
    source_files: x_train.txt,x_test.txt
    encodings_file: word_encodings.csv
    keymappings:
      inputs: tokenized_sentences
      outputs: encoded_sentences
  bow_encoder:
    type: BOWEncoder
    priority: 3
    keymappings:
      inputs: encoded_sentences
      outputs: bow_sencentes
      bow_size: sentence_vocab_size # Set by sentence_encoder.
  
  # Targets encoding.
  label_indexer:
    type: LabelIndexer
    priority: 4
    data_folder: ~/data/language_identification/wily
    source_files: y_train.txt,y_test.txt
    encodings_file: language_name_encodings.csv
    keymappings:
      inputs: languages
      outputs: indexed_languages
  
  # Model
  classifier:
    type: SoftmaxClassifier
    #freeze: True
    priority: 5
    keymappings:
      inputs: bow_sencentes
      #predictions: encoded_predictions
      input_size: sentence_vocab_size # Set by sentence_encoder.
      prediction_size: label_vocab_size # Set by target_encoder.
  
  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    keymappings:
      targets: indexed_languages
      #predictions: encoded_predictions
      loss: loss
  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 8
    data_folder: ~/data/language_identification/wily
    encodings_file: language_name_encodings.csv
    keymappings:
      inputs: predictions
      outputs: predicted_labels

  # Statistics.
  batch_size:
    type: BatchSize
    priority: 9
  accuracy:
    type: Accuracy
    priority: 10
    keymappings:
      targets: indexed_languages

  #: pipeline
