# This file defines the default values for the Accuracy statistics.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be loaded by the component.
####################################################################

keymappings: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing targets (label ids) (INPUT)
  targets: targets

  # Stream containing batch of predictions (INPUT)
  predictions: predictions

  ####################################################################
  # 3. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be RETRIEVED.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be SET.
  ####################################################################

  # Name used for collected statistics.
  accuracies: accuracies

