# Load config defining MNIST tasks for training, validation and testing.
default_configs: molecule_classification/default_molecule_classification.yml

# Pipeline - only the model-related components.
pipeline:
  # Model 1: 3 CNN layers.
  image_encoder:
    type: ConvNetEncoder
    priority: 1
    # Using default stream names, so the following could be removed (leaving it just for the clarity though).
    streams:
      inputs: images
      feature_maps: feature_maps

  # Reshape inputs
  reshaper:
    type: ReshapeTensor
    # TODO: change!
    #input_dims: [-1, 16, 107, 107]
    #output_dims: [-1, 183184]
    input_dims: [-1, 16, 9, 9]
    output_dims: [-1, 1296]
    priority: 2
    streams:
      inputs: feature_maps
      outputs: reshaped_maps
    globals:
      output_size: reshaped_maps_size

  # Model 2: 1 Fully connected layer with softmax acitvation.
  classifier:
    type: FeedForwardNetwork 
    priority: 3
    streams:
      inputs: reshaped_maps
      # Using default stream name, so the following could be removed (leaving it just for the clarity though).
      predictions: predictions
    globals:
      input_size: reshaped_maps_size
      prediction_size: num_classes

#: pipeline
