# Load config defining MNIST tasks for training, validation and testing.
default_configs: mnist/default_mnist.yml

# Training parameters - overwrite defaults:
training:
  task: 
    resize_image: [32, 32]

# Validation parameters - overwrite defaults:
validation:
  task:
    resize_image: [32, 32]

# Testing parameters - overwrite defaults:
test:
  task:
    resize_image: [32, 32]

# Definition of the pipeline.
pipeline:

  # Image classifier.
  image_classifier:
    type: LeNet5
    priority: 1
    globals:
      prediction_size: num_classes

#: pipeline
