# Load config defining MNIST problems for training, validation and testing.
default_configs: mnist/default_mnist.yml

pipeline:
  name: mnist_softmax_classifier
  #disable: nllloss

  # Reshapes tensors.
  reshaper:
    type: ReshapeTensor
    input_dims: [-1, 1, 28, 28]
    output_dims: [-1, 784]
    priority: 1
    keymappings:
      outputs: reshaped_images
      output_size: reshaped_image_size

  # Classifier.
  classifier:
    type: SoftmaxClassifier 
    priority: 2
    hidden_sizes: [100, 100]
    keymappings:
      inputs: reshaped_images
      input_size: reshaped_image_size
      prediction_size: num_classes

  # Loss
  nllloss:
    type: NLLLoss
    priority: 3
  
  # Statistics.
  batch_size:
    type: BatchSize
    priority: 4
  accuracy:
    type: Accuracy
    priority: 5


#: pipeline
