# This file defines the default values for the CIFAR-100 problem.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Folder where problem will store data (LOADED)
data_folder: '~/data/cifar-100'

# Defines the set that will be used used (LOADED)
# True: training set | False: test set.
use_train_data: True

# Optional parameter (LOADED)
# When present, resizes the CIFAR images from [32,32] to [width, height]
#resize_image: [height, width]

streams:
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of indices (OUTPUT)
  # Every problem MUST return that stream.
  indices: indices

  # Stream containing batch of images (OUTPUT)
  images: images

  # Streams containing targets (label ids) (OUTPUT)
  coarse_targets: coarse_targets
  fine_targets: fine_targets

  # Streams containing labels (words) (OUTPUT)
  coarse_labels: coarse_labels
  fine_labels: fine_labels

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Width of the image (SET)
  input_width: image_width
  # Height of the image (SET)
  input_height: image_height
  # Depth of the image (SET)
  input_depth: image_depth
  
  # Numbers of output classes (SET)
  coarse_num_classes: coarse_num_classes
  fine_num_classes: fine_num_classes

  # Labels (word-idx) mappings (SET)
  coarse_label_word_mappings: coarse_label_word_mappings
  fine_label_word_mappings: fine_label_word_mappings

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

