# This file defines the default values for the MNIST problem.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be loaded by the model.
####################################################################

# Folder where problem will store data.
data_folder: '~/data/mnist'

# Defines the set that will be used used. True: training set | False: test set.
use_train_data: True

# Optional parameter: when present, resizes the MNIST images from [28,28] to [width, height]
#resize = [height, width]

####################################################################
# 2. Keymappings associated with INPUT and OUTPUT streams.
####################################################################

# Stream containing batch of images (OUTPUT)
inputs: inputs

# Stream containing targets (label ids) (OUTPUT)
targets: targets

####################################################################
# 3. Keymappings associated with GLOBAL variables that will be SET.
####################################################################

# Width of the image (SET)
input_width: image_width
# Height of the image (SET)
input_height: image_height
# Depth of the image (SET)
input_depth: image_depth

####################################################################
# 4. Keymappings associated with GLOBAL variables that will be RETRIEVED.
####################################################################

