# This file defines the default values for the MNIST problem.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Folder where problem will store data (LOADED)
data_folder: '~/data/mnist'

# Defines the set that will be used used (LOADED)
# True: training set | False: test set.
use_train_data: True

# Optional parameter (LOADED)
# When present, resizes the MNIST images from [28,28] to [width, height]
#resize = [height, width]

streams:
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of indices (OUTPUT)
  # Every problem MUST return that stream.
  indices: indices

  # Stream containing batch of images (OUTPUT)
  inputs: inputs

  # Stream containing targets (label ids) (OUTPUT)
  targets: targets

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Width of the image (SET)
  input_width: image_width
  # Height of the image (SET)
  input_height: image_height
  # Depth of the image (SET)
  input_depth: image_depth

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

