# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/c3_classification/default_c3_classification.yml

pipeline:

  global_publisher:
    type: GlobalVariablePublisher
    priority: 0
    # Add input_size to globals.
    keys: [image_size_dims,image_latent_size,image_size_latent_size]
    values: [2,100,10]

  # 2nd subpipeline: image size.
  # Model - image size classifier.
  image_size_ffn:
    type: FeedForwardNetwork 
    #hidden_sizes: [100]
    priority: 2
    streams:
      inputs: image_sizes
      predictions: image_size_activations
    globals:
      input_size: image_size_dims
      prediction_size: image_latent_size

  # 3rd subpipeline: image.
  # Image encoder.
  image_encoder:
    type: ConvNetEncoder
    priority: 3.1
    streams:
      inputs: images

  # Reshape inputs
  reshaper:
    type: ReshapeTensor
    input_dims: [-1, 16, 26, 26]
    output_dims: [-1, 10816]
    priority: 3.2
    streams:
      inputs: feature_maps
      outputs: reshaped_maps
    globals:
      output_size: reshaped_maps_size

  # Model - feed-forward.
  image_ffn:
    type: FeedForwardNetwork 
    hidden_sizes: [1000]
    priority: 3.3
    streams:
      inputs: reshaped_maps
      predictions: image_activations
    globals:
      input_size: reshaped_maps_size
      prediction_size: image_size_latent_size

  # 4th subpipeline: concatenation + FF.
  concat:
    type: Concatenation
    priority: 4.1
    input_streams: [image_size_activations,image_activations]
    # Concatenation 
    dim: 1 # default
    input_dims: [[-1,100],[-1,10]]
    output_dims: [-1,110]
    streams:
      outputs: concatenated_activations
    globals:
      #input_sizes: [latent_size,latent_size,latent_size]
      output_size: output_size


  classifier:
    type: FeedForwardNetwork 
    hidden_sizes: [50]
    priority: 4.2
    streams:
      inputs: concatenated_activations
    globals:
      input_size: output_size
      prediction_size: vocabulary_size_c3


  #: pipeline
