# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/c3_classification/default_c3_classification.yml

pipeline:
  name: vqa_med_c3_classification_question_onehot_bow

  # Questions encoding.
  question_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  question_onehot_encoder:
    type: SentenceOneHotEncoder
    priority: 1.2
    data_folder: ~/data/vqa-med
    word_mappings_file: questions.all.word.mappings.csv
    export_word_mappings_to_globals: True
    streams:
      inputs: tokenized_questions
      outputs: encoded_questions
    globals:
      vocabulary_size: sentence_vocabulary_size

  question_bow_encoder:
    type: BOWEncoder
    priority: 1.3
    streams:
      inputs: encoded_questions
      outputs: bow_questions
    globals:
        bow_size: sentence_vocabulary_size

  # Model.
  classifier:
    type: FeedForwardNetwork 
    hidden_sizes: [100, 100]
    priority: 3
    streams:
      inputs: bow_questions
    globals:
      input_size: sentence_vocabulary_size
      prediction_size: vocabulary_size_c3
  
#: pipeline
