  # Load config defining tasks for training, validation and testing.
default_configs: vqa_med_2019/c3_classification/default_c3_classification.yml

pipeline:

  # Image encoder.
  image_encoder:
    type: GenericImageEncoder
    priority: 1.1
    streams:
      inputs: images
      outputs: vgg_images
    globals:
      output_size: vocabulary_size_c3

  # Model - softmax classifier.
  classifier:
    type: FeedForwardNetwork 
    priority: 3
    streams:
      inputs: vgg_images
    globals:
      input_size: vocabulary_size_c3
      prediction_size: vocabulary_size_c3
  
#: pipeline
