# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/c3_classification/default_c3_classification.yml

training:
  problem:
    resize_image: &resize_image [28, 28]

validation:
  problem:
    resize_image: *resize_image


pipeline:

  # Reshape inputs
  reshaper:
    type: ReshapeTensor
    priority: 1.1
    input_dims: [-1, 3, 28, 28]
    output_dims: [-1, 2352]
    streams:
      inputs: images
      outputs: reshaped_maps
    globals:
      output_size: reshaped_maps_size

  # Model - softmax classifier.
  classifier:
    type: FeedForwardNetwork 
    priority: 1.2
    hidden: [100]
    streams:
      inputs: reshaped_maps
    globals:
      input_size: reshaped_maps_size
      prediction_size: vocabulary_size_c3
  
#: pipeline
