# This pipeline applies seq2seq on wikitext-2 to make word-level prediction.
# It's been made for test purposes only, as it is doing:
# [word 0 , ... , word 49] -> [word 1 , ... , word 50] (basically copying most of the input)
#
# The seq2seq here is implemented throught the use of 2 `RecurrentNeuralNetwork`

# Training parameters:
training:
  problem:
    type: &p_type WikiTextLanguageModeling
    data_folder: &data_folder ~/data/language_modeling/wikitext-2
    dataset: &dataset wikitext-2
    subset: train
    sentence_length: 50
    batch_size:  64

  # optimizer parameters:
  optimizer:
    name: Adam
    lr: 1.0e-3

  # settings parameters
  terminal_conditions:
    loss_stop: 1.0e-2
    episode_limit: 1000000
    epoch_limit: 100

# Validation parameters:
validation:
  partial_validation_interval: 100
  problem:
    type: *p_type
    data_folder: *data_folder
    dataset: *dataset
    subset: valid
    sentence_length: 50
    batch_size:  64

# Testing parameters:
testing:
  problem:
    type: *p_type 
    data_folder: *data_folder
    dataset: *dataset
    subset: test
    sentence_length: 50
    batch_size: 64

pipeline:
  name: wikitext_language_modeling_seq2seq

  # Source encoding - model 1.
  source_sentence_embedding:
    type: SentenceEmbeddings
    priority: 1.1
    embeddings_size: 50
    pretrained_embeddings: glove.6B.50d.txt
    data_folder: *data_folder
    source_vocabulary_files: wiki.train.tokens,wiki.valid.tokens,wiki.test.tokens
    vocabulary_mappings_file: wiki.all.tokenized_words
    additional_tokens: <eos>
    export_word_mappings_to_globals: True
    streams:
      inputs: sources
      outputs: embedded_sources
        
  # Target encoding.
  target_indexer:
    type: SentenceIndexer
    priority: 2.1
    data_folder: *data_folder
    import_word_mappings_from_globals: True
    streams:
      inputs: targets
      outputs: indexed_targets

  # Publish the hidden size of the seq2seq
  global_publisher:
    type: GlobalVariablePublisher
    priority: 1
    # Add input_size to globals, so classifier will use it.
    keys: s2s_hidden_size
    values: 300

  # FF, to resize the embeddings to whatever the hidden size of te seq2seq is.
  ff_resize_s2s_input:
    type: FeedForwardNetwork 
    priority: 2.5
    s2s_hidden_size: 300
    use_logsoftmax: False
    dimensions: 3
    streams:
      inputs: embedded_sources
      predictions: embedded_sources_resized
    globals:
      input_size: embeddings_size
      prediction_size: s2s_hidden_size
  
  # LSTM Encoder
  lstm_encoder:
    type: RecurrentNeuralNetwork
    priority: 3
    initial_state: Trainable
    hidden_size: 300
    num_layers: 3
    use_logsoftmax: False
    output_last_state: True
    prediction_mode: Last
    streams:
      inputs: embedded_sources_resized
      predictions: s2s_encoder_output
      output_state: s2s_state_output
    globals:
      input_size: s2s_hidden_size
      prediction_size: s2s_hidden_size 

  # LSTM Decoder
  lstm_decoder:
    type: RecurrentNeuralNetwork
    priority: 4
    initial_state: Input
    hidden_size: 300
    num_layers: 3
    use_logsoftmax: False
    input_mode: Autoregression_First
    autoregression_length: 50
    prediction_mode: Dense
    streams:
      inputs: s2s_encoder_output
      predictions: s2s_decoder_output
      input_state: s2s_state_output
    globals:
      input_size: s2s_hidden_size
      prediction_size: s2s_hidden_size 

  # FF, to resize the from the hidden size of the seq2seq to the size of the target vector
  ff_resize_s2s_output:
    type: FeedForwardNetwork 
    use_logsoftmax: True
    dimensions: 3
    priority: 5
    streams:
      inputs: s2s_decoder_output
    globals:
      input_size: s2s_hidden_size
      prediction_size: vocabulary_size

  # Loss
  nllloss:
    type: NLLLoss
    priority: 6
    num_targets_dims: 2
    streams:
      targets: indexed_targets
      loss: loss

  # Prediction decoding.
  prediction_decoder:
    type: SentenceIndexer
    priority: 10
    # Reverse mode.
    reverse: True
    # Use distributions as inputs.
    use_input_distributions: True
    data_folder: *data_folder
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: prediction_sentences


  # Statistics.
  batch_size:
    type: BatchSizeStatistics
    priority: 100.0

  #accuracy:
  #  type: AccuracyStatistics
  #  priority: 100.1
  #  streams:
  #    targets: indexed_targets

  bleu:
    type: BLEUStatistics
    priority: 100.2
    streams:
      targets: indexed_targets

      
  # Viewers.
  viewer:
    type: StreamViewer
    priority: 100.3
    input_streams: sources,targets,indexed_targets,prediction_sentences

#: pipeline
