# This file defines the default values for the PrecisionRecall statistics.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Flag indicating whether prediction are represented as distributions or indices (LOADED)
# Options: True (expects distribution for each preditions)
#          False (expects indices (max args))
use_prediction_distributions: True

# Flag indicating whether confusion matrix will be shown (LOADED)
show_confusion_matrix: False

# Flag indicating whether detailed scores for each class will be shown (LOADED)
show_class_scores: False

# When set to true, will use the provided word mappings as labels (LOADED)
use_word_mappings: False

# When set to True, performs masking of selected samples from batch (LOADED)
use_masking: False

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing targets (label ids) (INPUT)
  targets: targets

  # Stream containing batch of predictions (INPUT)
  predictions: predictions

  # Stream containing masks used for masking of selected samples from batch (INPUT)
  masks: masks

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  # Word mappings (optionally) used as labels (RETRIEVED)
  word_mappings: word_mappings

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

statistics:
  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

  # Names used for collected statistics (ADDED).
  precision: precision
  recall: recall
  f1score: f1score


