# This file defines the default values for the Stream File Exporter.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# List of names of streams that will be displayed (LOADED)
# Can be string a single name or or comma separated string with list
input_streams: ''

# Separator that will be placed between values (LOADED)
separator: ','

# Adds additional line to output file enabling Excel to use different separator while loading (LOADED)
export_separator_line_to_csv: False

# Adds additional line to output with header (LOADED)
export_header_to_csv: False

# Name of the file containing output values (LOADED)
filename: 'outputs.txt'

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

