# This file defines the default values for the Multimodal Compact Bilinear Pooling model.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Parameter denoting whether projection matrices are trainable (LOADED)
# Setting flag that to true will result in trainable, dense (i.e. not "sketch") projection layers.
trainable_projections: False

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of encoded images (INPUT)
  image_encodings: image_encodings

  # Stream containing batch of encoded questions (INPUT)
  question_encodings: question_encodings

  # Stream containing outputs (OUTPUT)
  outputs: outputs

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  # Size of the image encodings input (RETRIEVED)
  image_encoding_size: image_encoding_size

  # Size of the question encodings input (RETRIEVED)
  question_encoding_size: question_encoding_size

  # Size of the output (RETRIEVED)
  output_size: output_size

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

