# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/question_categorization/default_question_categorization.yml

pipeline:
  name: vqa_med_question_categorization_rnn

  # Questions encoding.
  question_tokenizer:
    type: SentenceTokenizer
    priority: 1.1
    streams: 
      inputs: questions
      outputs: tokenized_questions

  # Model 2: Embeddings
  question_embeddings:
    type: SentenceEmbeddings
    priority: 1.2
    embeddings_size: 50
    pretrained_embeddings_file: glove.6B.50d.txt
    data_folder: ~/data/vqa-med
    word_mappings_file: questions.all.word.mappings.csv
    streams:
      inputs: tokenized_questions
      outputs: embedded_questions      
  
  # Model 2: RNN
  lstm:
    type: RecurrentNeuralNetwork
    cell_type: LSTM
    prediction_mode: Last
    priority: 3
    initial_state_trainable: False
    #num_layers: 5
    #hidden_size: 1000
    streams:
      inputs: embedded_questions
    globals:
      input_size: embeddings_size
      prediction_size: num_categories # C1,C2,C3,C4

#: pipeline
