# This file defines the default values for the NLL Loss.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Number of dimensions of targets, so the loss can work with 
# diffent inputs/targets (LOADED)
num_targets_dims: 1

# Loss function (LOADED)
# Options: NLLLoss | CrossEntropyLoss (NOT OPERATIONAL YET!)
# loss_function: NLLLoss

# When set to True, performs masking of selected samples from batch (LOADED)
use_masking: False

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing targets (label ids) (INPUT)
  targets: targets

  # Stream containing batch of predictions (INPUT)
  predictions: predictions

  # Stream containing masks used for masking of selected samples from batch (INPUT)
  masks: masks

  # Stream containing loss (OUTPUT)
  loss: loss

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

