# Load config defining problems for training, validation and testing.
default_configs: vqa_med_2019/default_vqa_med_2019.yml

# Training parameters:
training:
  problem:
    categories: C1

# Validation parameters:
validation:
  problem:
    categories: C1

pipeline:

  # Predictions decoder.
  prediction_decoder:
    type: WordDecoder
    priority: 10.1
    # Use the same word mappings as label indexer.
    import_word_mappings_from_globals: True
    streams:
      inputs: predictions
      outputs: predicted_answers
    globals:
      vocabulary_size: vocabulary_size_ci1
      word_mappings: word_mappings_c1

  # Loss
  nllloss:
    type: NLLLoss
    priority: 10.2
    targets_dim: 1
    streams:
      targets: answers_ids
      loss: loss

  # Statistics.
  accuracy:
    type: AccuracyStatistics
    priority: 100.1
    streams:
      targets: answers_ids
  batch_size:
    type: BatchSizeStatistics
    priority: 100.2

  # Viewers.
  viewer:
    type: StreamViewer
    priority: 100.3
    stream_names: questions,category_names,answers,predicted_answers

#: pipeline
