# Training parameters:
training:
  task: 
    type: CLEVR
    batch_size: &b 64
    split: training
    #resize_image: [224, 224]
  # optimizer parameters:
  optimizer:
    type: Adam
    lr: 0.0001
  # settings parameters
  terminal_conditions:
    loss_stop_threshold: 0.05
    early_stop_validations: -1
    episode_limit: 10000
    epoch_limit: 10

# Validation parameters:
validation:
  task:
    type: CLEVR
    batch_size: *b
    split: validation
    #resize_image: [224, 224]

# Testing parameters:
test:
  task:
    type: CLEVR
    batch_size: *b
    split: test
    #resize_image: [224, 224]

pipeline:
  name: tmp
  disable: image_viewer

  label_to_target:
    type: LabelIndexer
    priority: 0.1
    # Load word mappings for answers.
    data_folder: ~/data/CLEVR_v1.0
    word_mappings_file: answers.all.word.mappings.csv
    export_word_mappings_to_globals: True
    globals:
      word_mappings: answer_word_mappings
      vocabulary_size: num_answers
    streams:
      inputs: answers 
      outputs: target_answers


  # Loss
  nllloss:
    type: NLLLoss
    priority: 10.1
    streams:
      targets: target_answers

  # Statistics.
  batch_size:
    priority: 100.0
    type: BatchSizeStatistics

  accuracy:
    priority: 100.1
    type: AccuracyStatistics
    streams:
      targets: target_answers

  precision_recall:
    priority: 100.2
    type: PrecisionRecallStatistics
    use_word_mappings: True
    show_class_scores: True
    globals:
      word_mappings: answer_word_mappings
    streams:
      targets: target_answers

  answer_decoder:
    priority: 100.3
    type: WordDecoder
    import_word_mappings_from_globals: True
    globals:
      word_mappings: answer_word_mappings
    streams:
      inputs: predictions
      outputs: predicted_answers

  stream_viewer:
    priority: 100.4
    type: StreamViewer
    input_streams: indices, questions, target_answers, predicted_answers

  #image_viewer:
  #  priority: 100.5
  #  type: ImageViewer
  #  streams:
  #    images: inputs
  #    labels: labels
  #    answers: answers

