# This file defines the default values for the VQAMED2019 problem.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Folder where problem will store data (LOADED)
data_folder: '~/data/vqa-med'

# Defines the set (split) that will be used (LOADED)
# Options: training | validation | test
split: training

# Defines the categoriees that will be used (LOADED)
# Options: all | c1 | c2 | c3 | c4 (or any combination of the latter 4)
categories: all

# Removes punctuation (LOADED)
# Options: none | questions | answers | all
remove_punctuation: questions

# Resize parameter (LOADED)
# When present, resizes the images from original size to [height, width]
# Depth remains set to 3.
#resize_image: [height, width]

# Scale parameter [height, width] (LOADED)
# Problem will use those values to rescale the image_sizes to range (0, 1).
scale_image_size: [2414, 2323]

# Set augmentation parameter
# Use random affine transformations (rotate, scale and translate)
use_augmentation: True

streams:
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of indices (OUTPUT)
  # Every problem MUST return that stream.
  indices: indices

  # Stream containing batch of images (OUTPUT)
  images: images

  # Stream containing batch of image names (OUTPUT)
  image_ids: image_ids

  # Stream containing batch with original sizes of images (OUTPUT)
  image_sizes: image_sizes

  # Stream containing batch of questions (OUTPUT)
  questions: questions

  # Stream containing targets - answers (OUTPUT)
  answers: answers

  # Stream containing batch with question categories - indices (OUTPUT)
  category_ids: category_ids

  # Stream containing batch with question categories - names (OUTPUT)
  category_names: category_names

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Width of the image (SET)
  input_width: image_width
  # Height of the image (SET)
  input_height: image_height
  # Depth of the image (SET)
  input_depth: image_depth
  # Category (word-idx) mappings (SET)
  category_word_mappings: category_word_mappings

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################
