# This file defines the default values for the LeNet5 model.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be loaded by the component.
####################################################################

keymappings: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of images (INPUT)
  inputs: inputs

  # Stream containing predictions (OUTPUT)
  predictions: predictions

  ####################################################################
  # 3. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be RETRIEVED.
  ####################################################################

  # Size of the prediction (GET)
  prediction_size: prediction_size
