# This file defines the default values for the Sentence Embeddings.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Folder where problem will store data (LOADED)
data_folder: '~/data/'

# File containing pretrained embeddings (LOADED)
# Empty means that no embeddings will be loaded.
# Options: 
pretrained_embeddings: ''

# Source files that will be used to create the vocabulary  (LOADED)
source_vocabulary_files: ''

# File containing resulting (LOADED)
vocabulary_mappings_file: 'default_mappings.csv'

# If set, component will always (re)generate vocabulary (LOADED)
# True means that it will be regenerated despite the existence of file.
regenerate: False 

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of inputs (INPUT)
  inputs: inputs

  # Stream containing predictions (OUTPUT)
  predictions: predictions

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # The created vocabulary (SET)
  vocabulary: vocabulary

  # Size of the vocabulary (SET)
  vocabulary_size: vocabulary_size

  # Size of the embeddings (SET)
  # It is exported to globals, so other components can use it during
  # their initialization.
  embeddings_size: embeddings_size

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

