# This file defines the default values for the Variational Flow LeNet5 model.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of images (INPUT)
  inputs: inputs

  # Stream containing batch of targets (used for masks) (INPUT)
  targets: targets

  # Streams containing predictions (OUTPUT)
  flow1_predictions: flow1_predictions
  flow2_predictions: flow2_predictions

  # Streams containing predictions (OUTPUT)
  flow1_masks: flow1_masks
  flow2_masks: flow2_masks

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  # Size of the prediction (RETRIEVED)
  flow1_prediction_size: flow1_prediction_size
  flow2_prediction_size: flow2_prediction_size
  
  # Word mappings used for filtering.
  flow1_word_mappings: flow1_word_mappings
  flow2_word_mappings: flow2_word_mappings

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

