# This file defines the default values for the ElementWiseMultiplication model.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Dropout rate (LOADED)
# Default: 0 (means that it is turned off)
dropout_rate: 0

# Number of hidden layers, along with their sizes (numbers of neurons) (LOADED)
hidden_sizes: [256, 256]

# Size of the output of g_theta network/output after concatenation (LOADED)
output_size: 256

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing batch of encoded images (INPUT)
  feature_maps: feature_maps

  # Stream containing batch of encoded questions (INPUT)
  question_encodings: question_encodings

  # Stream containing outputs (OUTPUT)
  outputs: outputs

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  # Height of the features tensor (RETRIEVED)
  feature_maps_height: feature_maps_height

  # Width of the features tensor (RETRIEVED)
  feature_maps_width: feature_maps_width

  # Depth of the features tensor (RETRIEVED)
  feature_maps_depth: feature_maps_depth

  # Size of the question encodings input (RETRIEVED)
  question_encoding_size: question_encoding_size

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # Size of the output (SET)
  output_size: output_size

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

