# This file defines the default values for Label Indexer.

####################################################################
# 1. CONFIGURATION PARAMETERS that will be LOADED by the component.
####################################################################

# Folder where problem will store data (LOADED)
data_folder: '~/data/'

# Source files that will be used to create the vocabulary  (LOADED)
source_vocabulary_files: ''

# Additional tokens that will be added to vocabulary (LOADED)
additional_tokens: ''

# File containing word (LOADED)
word_mappings_file: 'word_mappings.csv'

# If set, component will always (re)generate the vocabulary (LOADED)
regenerate: False 

streams: 
  ####################################################################
  # 2. Keymappings associated with INPUT and OUTPUT streams.
  ####################################################################

  # Stream containing input tensor (INPUT)
  inputs: inputs

  # Stream containing output tensor (OUTPUT)
  outputs: outputs

globals:
  ####################################################################
  # 3. Keymappings of variables that will be RETRIEVED from GLOBALS.
  ####################################################################

  ####################################################################
  # 4. Keymappings associated with GLOBAL variables that will be SET.
  ####################################################################

  # The created word mappings (SET)
  word_mappings: word_mappings

  # Size of the vocabulary (SET)
  vocabulary_size: vocabulary_size

  ####################################################################
  # 5. Keymappings associated with statistics that will be ADDED.
  ####################################################################

